name: travlr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  domain:
    path: ./packages/domain
  data:
    path: ./packages/data
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  gap: ^3.0.1
  intl: ^0.18.1
  go_router: ^13.0.1
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true # Auto-generate language files
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/icons/logo_launcher.png"
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#4f6628"
    theme_color: "#4f6628"
  macos:
    generate: true